---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/
        - name: promtail-config
          configMap: 
            name: promtail-config
      containers:
        - name: promtail-container
          image: grafana/promtail
          securityContext:
            privileged: true          
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: varlog
              mountPath: /var/log/
            - name: promtail-config
              mountPath: /etc/promtail
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |  
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://monitoring:3100/loki/api/v1/push
    scrape_configs:
      - job_name: containers
        static_configs:
        - targets:
            - localhost
          labels:
            job: containers
            __path__: /var/log/containers/*log
