apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: # Host name that corresponds to the "known_hosts" below, ex github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: # zcash-in-a-box-sec.b64 contents here
  known_hosts: # git_host.pub contents here
