---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-script-miner-tnb-artifacts
data:
  ZCASHD_BINARY_TGZ: zcashd-tnb-artifacts-ab2b7c0.tgz
  ZCASHD_SNAPSHOT: zcash-testnet-miner-tnb-test3.tgz
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-script-miner-master-artifacts
data:
  ZCASHD_BINARY_TGZ: zcashd-artifacts-ab2b7c0.tgz
  ZCASHD_SNAPSHOT: zcash-testnet-miner-tnb-test3.tgz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcashd-testnet-miner-config
data:
  ZCASHD_RPCPORT: "38232"
  zcash.conf: |
    listen=1
    testnet=1
    showmetrics=0
    logips=1
    dns=0
    gen=1
    experimentalfeatures=1
    txindex=1
    insightexplorer=0
    printtoconsole=1
    equihashsolver=tromp
    genproclimit=4
    rpcuser=zcashrpc
    rpcport=38232
