---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miners
  template:
    metadata:
      labels:
        app: miners
        network: tze
    spec:
      volumes:
        - name: zcashconf
          configMap:
            name: zcashd-tze-testnet-miner-config  
      containers:
        - name: zcashd-script
          image: electriccoinco/zcash-in-a-box-runner:latest
          volumeMounts:
            - name: zcashconf
              mountPath: /workspace/zcashconf            
          env:
            - name: ZCASHD_BINARY_TGZ
              value: zcashd-tze-artifacts-5c7e3c4.tgz
            - name: Z_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret-key
                  key: SECRETACCESSKEY
            - name: ZCASHD_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zcashd-rpc
                  key: password
          args:
            - bash
            - -c
            - |
              set -e -o pipefail
              set -x
              ls -l
              env | sort
              # Configure the minio client
              mc config host add zcash-in-a-box http://minio:9000 minio ${Z_SECRETACCESSKEY} --api S3v4
              # Get zcash network parameters
              mc cp -r zcash-in-a-box/cache/zcash-params/ ${HOME}/.zcash-params/
              # Get zcashd artifacts
              mc cp zcash-in-a-box/binaries/${ZCASHD_BINARY_TGZ} zcashd-artifacts.tgz
              tar zxvf zcashd-artifacts.tgz
              # Copy the configmap, because reasons
              mkdir -p ${HOME}/.zcash
              cp /workspace/zcashconf/zcash.conf ${HOME}/.zcash/zcash.conf
              cat ${HOME}/.zcash/zcash.conf
              /workspace/source/src/zcashd
        - name: zcashd-exporter
          image: electriccoinco/zcashd_exporter
          command:
            - /go/bin/zcashd_exporter
          args:
            - --web.listen-address
            - :9100
            - --rpc.port
            - $(ZCASHD_RPCPORT)
            - --rpc.user
            - $(ZCASHD_RPCUSER)
            - --rpc.password
            - $(ZCASHD_RPCPASSWORD)
          env:
            - name: ZCASHD_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zcashd-rpc
                  key: password               
          ports:
            - name: zcashd-exporter
              containerPort: 9100