---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zcash-script-miner-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zcash-script-miner
  template:
    metadata:
      labels:
        app: zcash-script-miner
        network: zcash-script
    spec:
      volumes:
        - name: zcashconf
          configMap:
            name: zcashd-tze-testnet-miner-config  
      containers:
        - name: zcashd-script
          image: electriccoinco/zcash-in-a-box-runner:latest
          volumeMounts:
            - name: zcashconf
              mountPath: /workspace/zcashconf
          envFrom:
            - configMapRef:
                name: zcashd-testnet-master              
          env:
            - name: Z_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret-key
                  key: SECRETACCESSKEY
            - name: ZCASHD_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zcashd-rpc
                  key: password
          args:
            - bash
            - -c
            - |
              set -e -o pipefail
              set -x
              ls -l
              env | sort
              # Configure the minio client
              mc config host add zcash-in-a-box http://minio:9000 minio ${Z_SECRETACCESSKEY} --api S3v4
              # Copy zcash network parameters
              mc cp -r zcash-in-a-box/cache/zcash-params/ ${HOME}/.zcash-params/
              # Get a zcashd binary
              mc cp zcash-in-a-box/binaries/${ZCASHD_BINARY_TGZ} zcashd-artifacts.tgz
              tar zxvf zcashd-artifacts.tgz
              # Get a zcash network snapshot
              export ZCASHD_SNAPSHOT=zcash-testnet3-809421.tgz
              mc cp zcash-in-a-box/cache/${ZCASHD_SNAPSHOT} blocks_snapshot.tgz
              export ZCASH_BLOCK_DIR=testnet3
              mkdir -p ${HOME}/.zcash/${ZCASH_BLOCK_DIR}
              tar zxvf blocks_snapshot.tgz -C ${HOME}/.zcash/${ZCASH_BLOCK_DIR}
              # Get a zcashd configuration
              # 
              sleep infinity
              /workspace/source/src/zcashd -testnet -gen=1 -printtoconsole -showmetrics=0 -equihashsolver=tromp -genproclimit=2 -rpcuser=${ZCASHD_RPCUSER} -rpcpassword=${ZCASHD_RPCPASSWORD} -rpcport=${ZCASHD_RPCPORT}
        - name: zcashd-exporter
          image: electriccoinco/zcashd_exporter
          command:
            - /go/bin/zcashd_exporter
          args:
            - --web.listen-address
            - :9100
            - --rpc.port
            - $(ZCASHD_RPCPORT)
            - --rpc.user
            - $(ZCASHD_RPCUSER)
            - --rpc.password
            - $(ZCASHD_RPCPASSWORD)
          env:
            - name: ZCASHD_RPCPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zcashd-rpc
                  key: password
          envFrom:
            - configMapRef:
                name:  zcash-inabox-base                  
          ports:
            - name: zcashd-exporter
              containerPort: 9100