---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-test-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services"]
  verbs: ["create", "get", "list", "watch"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-test-rolebinding
subjects:
- kind: ServiceAccount
  name: kubectl-test
roleRef:
  kind: Role
  name: kubectl-test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-test-pod
spec:
  serviceAccountName: kubectl-test
  containers:
    - name: cloud-sdk
      image: google/cloud-sdk
      command: ["bash", "-c", "sleep infinity"]