---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zcash-inabox-configmap
data:
  ZCASHD_NETWORK: "mainnet"
  ZCASHD_RPCUSER: "zcashrpc"
  ZCASHD_LOGIPS: "1"
  ZCASHD_EXPERIMENTALFEATURES: "1"
  ZCASHD_TXINDEX: "1"
  ZCASHD_INSIGHTEXPLORER: "1"
  ZCASHD_ZMQPORT: "9904"
  ZCASHD_RPCBIND: "0.0.0.0"
  ZCASHD_RPCPORT: "38383"
  ZCASHD_ALLOWIP: "0.0.0.0/0"
