---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-cache
spec:
  type: ClusterIP
  ports:
    - name: ipfs-api
      port: 5001
      targetPort: 5001
    - name: api-gateway
      port: 8080
      targetPort: 8080
  selector:
    app: ipfs-cache