---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: zcashd-build-
spec:
  workspaces:
    - name: venv
      emptyDir: {}
  resources:
    inputs:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/zcash/zcash.git
  taskSpec:
    params:
      - name: MINIOHOST
        default: http://minio:9000
        type: string
      - name: MINIOBUCKET
        default: binaries
        type: string
      - name: COMMIT
        default: master
        type: string
      - name: JOBS
        default: "16"
        type: string
    resources:
      inputs:
        - name: source
          type: git
    workspaces:
        - name: venv
          mountPath: /venv
    steps:
      - name: setup-venv
        image: electriccoinco/zcashd-build:debian10
        script: |
          #!/bin/bash
          set -e -o pipefail
          pwd
          ls -al
          whoami
          python3 -m venv /venv/zcash-build-venv
          source /venv/zcash-build-venv/bin/activate
          python -m pip install pyblake2 pyflakes python-qpid-proton pyutil pyzmq requests simplejson
      - name: pyflakes
        image: electriccoinco/zcashd-build:debian10
        script: |
          #!/bin/bash
          set -e -o pipefail
          source /venv/zcash-build-venv/bin/activate
          pwd
          ls -l
          cd source
          pyflakes src zcutil
      - name: build
        image: electriccoinco/zcashd-build:debian10
        script: |
          #!/bin/bash
          set -ex -o pipefail
          cd source
          pwd
          ls -la
          echo $(git rev-parse --short HEAD) > /workspace/GIT_COMMIT
          ./zcutil/build.sh -j$(params.JOBS)
      - name: upload-file
        image: minio/mc
        env:
          - name: ACCESSKEYID
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: ACCESSKEYID 
          - name: SECRETACCESSKEY
            valueFrom:
              secretKeyRef:
                name: minio-secret-key
                key: SECRETACCESSKEY                        
        script: |
          #!/bin/sh
          env | sort
          set -xe -o pipefail
          export GIT_COMMIT=$(cat /workspace/GIT_COMMIT)
          mc config host add minio $(params.MINIOHOST) ${ACCESSKEYID} ${SECRETACCESSKEY}
          tar --strip-components 3 \
            -zvcf ./zcashd-artifacts-${GIT_COMMIT}.tgz \
            /workspace/source/src/zcashd \
            /workspace/source/src/zcash-cli \
            /workspace/source/src/zcash-gtest \
            /workspace/source/src/zcash-tx
          mc cp ./zcashd-artifacts-${GIT_COMMIT}.tgz minio/$(params.MINIOBUCKET)/
